services:
  - type: web
    name: global-trustdrive
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VAULTSAGE_API_KEY
        sync: false
